__base__:
  - config/base.yaml

experiment:
  run_name: squidiff-rna

dataset:
  data_path: data/mouse/processed/mouse_train.h5mu
  val_data_path: data/mouse/processed/mouse_val.h5mu
  rna_only: True

model:
  gene_size: 100
  loss_type: 'mse'

# python3 train_squidiff.py --config config/rna.yaml
